// <auto-generated />
namespace LeQuocBao_1811062386.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixCanceled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCanceled));
        
        string IMigrationMetadata.Id
        {
            get { return "202107061556470_FixCanceled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
